### PR TITLE
Enhance label filtering & display

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz 

With this change it is now possible to filter stories on their labels using a simple set algebra.
Also, when stories are listed, their labels are shown.

### CODE REVIEW

**Comment by jimlloyd** [comment]
This project currently doesn't have any unit tests. I may in the future use https://github.com/assaf/node-replay to add tests, but don't feel it is worth doing at this time.

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
