### PR TITLE
[Delivers #106771716, #106772338] bump command, start planned stories

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz this PR delivers two unrelated stories:
1) Add the 'bump' subcommand #106771716
2) Fix the bug that prevented current stories from being listed as startable

### CODE REVIEW

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
Added fixup. PTAL

**Comment by mhfrantz** [comment]
LGTM rebase

**Comment by jimlloyd** [comment]
Replaced by #8

**Pull request closed without merging**
